### ISSUE TITLE
Online Accounts is not responding [Google Account]

### ISSUE THREAD

**Issue by 3xploiton3** [xapp-project/gnome-online-accounts-gtk#12]
OS: Arch Linux x86_64
Kernel: 6.8.7-zen1-1-zen
DE: Cinnamon 6.0.4

![image](https://github.com/xapp-project/gnome-online-accounts-gtk/assets/19517680/c9697d98-5108-45bb-aab5-c3ac909e7805)

**Comment by clefebvre** [comment]
Hi @3xploiton3, please upgrade to 3.50.2. libAdwaita wasn't properly initiated in 3.50.1. It could be related? we're not really sure.
