### ISSUE TITLE
letters are not visible.

### ISSUE THREAD

**Issue by ritulahkar** [xapp-project/gnome-online-accounts-gtk#15]
When I open the app letters are not visible as shown below. Many apps are having similar issues. once cursor hovers some of them become visible.

![image](https://github.com/user-attachments/assets/008a0530-0d96-4ba5-b38c-55b88a32c377)

After mouse hover,

![image](https://github.com/user-attachments/assets/53a4deb8-9279-40f6-9de3-6f5b67b54fcd)

This no a specific issue of this app, but I don't know were to upload.

neofetch:

![Screenshot from 2024-07-28 20-26-04](https://github.com/user-attachments/assets/7a62cbea-0313-4717-a4c5-838a300aaa20)

**Comment by leigh123linux** [comment]
It a nvidia issue, see https://gitlab.gnome.org/GNOME/gtk/-/issues/6574
