### ISSUE TITLE
Can't ignore self signed / bad certificate

### ISSUE THREAD

**Issue by Wolkensteine** [xapp-project/gnome-online-accounts-gtk#16]
## What I am trying to do
I've a local NextCloud server that is just accessible in my LAN. I wanted to have https on it for push notifications and for just trying that out, so I set up a self signed cert for it, which worked well in Linux Mint 21 with the online accounts, I could easily synchronise the calendar and contacts with it (for the files I use the desktop synchronisation client).

## What happened
I formatted my harddrive and installed Linux Mint 22 Cinnamon edition, because I anyways had to clean my system and could upgrade like this too. Now the problem is that when I try to add the NextCloud account in "gnome online accounts gtk" I get prompted if I want to ignore the cert being self signed, but when I click "ignore" it doesn't appear to do anything. <br>
I'd be happy if someone could help me with this. Thank you in advance.

## System information:
OS: Linux Mint 22 Cinnamon edition
Cinnamon version: 6.2.7
Kernel: 6.8.0-39-generic
Display Server: X11
Processor: 12th Gen Intel© Core™ i7-12700H (with integrated graphics)
RAM: 16 GB

**Comment by mtwebster** [comment]
Looks like this issue:
https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/280

You should add a comment with your own specifics, though they OP's issue seems to be pretty much the same.

There's nothing we can do in gnome-online-accounts-gtk - all of the dialog and interaction beyond the main window is handled by this other project.
